# TODO: base image replicating the CDE (Cloudera Data Engineering) runtime:
#   - Python 3.x (match CDE version)
#   - PySpark (same major.minor as the cluster)
#   - Iceberg JARs for Spark
#   - soda-core-spark
#   - datacontract-cli
